### ISSUE TITLE
Off-by-One Typo in Configuration Options

### ISSUE THREAD

**Issue by hikarikuen** [MicrosoftDocs/azure-devops-server-docs#104]
In the [Configuration Options](https://docs.microsoft.com/en-us/azure/devops/server/install/get-started?view=azure-devops&branch=releasenotes%2FAzureDevOpsServer2020#configuration-options-basic-advanced-and-azure):

> The Server Configuration Wizard supports **two** main configuration options: Basic, Advanced, and Azure.

(emphasis changed)

I'm not sure about the history but I'm guessing the *Azure* option was added and the number wasn't updated.

I'm also not a GitHub expert, but if I could find `get-started.md` I'd be happy to submit a PR for a change this simple. Unfortunately the generated link below gives me a 404 so I'm not sure where I should be looking for the actual doc source. Doesn't look like this repo actually contains it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8513ef18-5fc7-ef6c-a671-30943022af39
* Version Independent ID: 8936e3dc-af12-3a32-9869-26c4a8f0975b
* Content: [Install and configure - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/install/get-started?view=azure-devops&branch=releasenotes%2FAzureDevOpsServer2020)
* Content Source: [docs/install/get-started.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/install/get-started.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
@hikarikuen - Thank you for the correction. I'm updating the article to correct as suggested.
