### ISSUE TITLE
"Team Foundation Administrators" group is no more available in Azure DevOps Server 2019 update 1.1

### ISSUE THREAD

**Issue by FrancescoSclano** [MicrosoftDocs/azure-devops-server-docs#107]
Rererring to https://docs.microsoft.com/en-us/azure/devops/server/admin/add-administrator?view=azure-devops-2019#add-a-user-to-the-server-administrators-group I didn't find in Azure DevOps Server 2019 update 1.1 the group named "Team Foundation Administrators". Furthermore, I dint't find a group name, for instance, "DevOps Administrators".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58706ad4-8f9d-8330-f7c7-532ee5e89f4a
* Version Independent ID: 7368607e-5924-8039-1105-bc55878429dd
* Content: [Add administrators - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/admin/add-administrator?view=azure-devops-2019#prerequisite)
* Content Source: [docs/admin/add-administrator.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/admin/add-administrator.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
@FrancescoSclano - THe Team Foundation Administrators group can be found through the Azure DevOps Server Administration Console, Gloose Administer Security. I'm updating the article to clarify.
