### ISSUE TITLE
Windows Server 2020 in Supported OSs?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-devops-server-docs#111]
I noticed that the 'Supported server operating systems' section mentions 'Windows Server 2020'. Couldn't find any info about it Microsoft's docs, only 2019: https://docs.microsoft.com/en-us/windows-server/.

Is this the correct info or is there any news on its way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf58945-edff-cb3b-ab71-d45d480f1044
* Version Independent ID: 8a1c8ac9-a829-837b-5e52-81766c1f545e
* Content: [Setup & upgrade requirements - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/requirements?view=azure-devops-2020#server-operating-systems)
* Content Source: [docs/requirements.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/requirements.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by justhchung** [comment]
Azure DevOps Server 2020 to be released will be supporting Windows Server 2020.
