### ISSUE TITLE
Is TFS 2018 supported in Windows Server 2019?

### ISSUE THREAD

**Issue by tomoshi-ms** [MicrosoftDocs/azure-devops-server-docs#115]
This page lists Windows Server 2016, Windows Server 2012 R2 and Windows Server 2012 as server OS that support TFS 2018.

[https://docs.microsoft.com/en-us/azure/devops/server/requirements?view=azure-devops-2020#server-operating-systems](url)
![image](https://user-images.githubusercontent.com/62641820/93601577-5b79b880-f9fc-11ea-9204-df99b71f62e7.png)

However, the following page states that Windows Server 2019 supports TFS 2018.

[https://docs.microsoft.com/en-us/windows-server/get-started-19/app-compat-19](url)
![image](https://user-images.githubusercontent.com/62641820/93601975-ec509400-f9fc-11ea-982b-3506305f4dc2.png)

Which information is correct?
Is TFS 2018 supported in Windows Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf58945-edff-cb3b-ab71-d45d480f1044
* Version Independent ID: 8a1c8ac9-a829-837b-5e52-81766c1f545e
* Content: [Setup & upgrade requirements - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/requirements?view=azure-devops-2020)
* Content Source: [docs/requirements.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/requirements.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by justhchung** [comment]
TFS 2018 is not supported with Windows Server 2019.
