### ISSUE TITLE
Are there any cost implications for upgrading TFS 2013 to latest Azure DevOps Server?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/azure-devops-server-docs#38]
Will there be any cost implication for upgrading TFS 2013 to Azure DevOps Server 2019?

How can one determine the cost implication of upgrading TFS 2013.
 --
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8a797fb-84e9-fb7b-d2d1-ad5f1f65af8c
* Version Independent ID: 03523a91-dfb5-edf3-fa1e-b4551cdb938d
* Content: [Upgrade requirements - TFS](https://docs.microsoft.com/en-us/azure/devops/server/upgrade/upgrade-2013/upgrade-2013-requirements?view=tfs-2013&viewFallbackFrom=azure-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fupgrade%2fupgrade-2013%2fupgrade-2013-requirements.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fupgrade%2fupgrade-2013%2fupgrade-2013-requirements.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Technology: **tfs-admin**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by nschonni** [comment]
Usually you're getting more stuff for free as you upgrade.
- Test hub at the basic level
- Package management at basic
- ...

**Comment by Anand-Moghe** [comment]
Got it.
