### ISSUE TITLE
Azure Active Directory should be a typo

### ISSUE THREAD

**Issue by wandersick** [MicrosoftDocs/azure-devops-server-docs#39]
"You can install Azure DevOps on more than one server if the servers are all joined to an Azure Active Directory domain that's based on a functional level that the servers support."

Here, "Azure Active Directory" should be "Active Directory"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf58945-edff-cb3b-ab71-d45d480f1044
* Version Independent ID: 8a1c8ac9-a829-837b-5e52-81766c1f545e
* Content: [Requirements for setup, upgrade, and administration - Azure DevOps Server & TFS](https://docs.microsoft.com/en-us/azure/devops/server/requirements?view=azure-devops#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2frequirements.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2frequirements.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Technology: **tfs-admin**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
@wandersick - Thank you for the correction. I am updating the article today.
