### ISSUE TITLE
Chart should be updated for version 2019

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/azure-devops-server-docs#4]
The chart ends with version 2018.X and should add version 2019.X

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84a54e9-baa1-521b-c6de-4edb2024e43e
* Version Independent ID: 181e6bb5-86e8-91e6-b3cf-9b554d4a97a0
* Content: [Upgrade your deployment - Azure DevOps Server & Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/server/upgrade/get-started?view=azure-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fupgrade%2fget-started.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fupgrade%2fget-started.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by ghost** [comment]
I agree with @filipiwinski. The only place I have seen this mentioned in in the Azure DevOps Server 2019 Release notes: https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019?view=azure-devops. In addition to updating the chart, the following statement needs to be made on THIS page: 

"Direct upgrade to Azure DevOps Server is supported from Team Foundation Server 2012 and newer. If your TFS deployment is on TFS 2010 or earlier, you need to perform some interim steps before upgrading to Azure DevOps Server 2019. "

**Comment by jmatcho** [comment]
The Previous Versions/Upgrade Path chart was JUST updated to include Version 2019 this week (although the date on this article is still not changed to be current).

Bottom line:  You can upgrade directly to 2019 from several prior versions.

**Comment by pdeveau** [comment]
The chart says you can go from 2012 directly to 2019, this appears to not be the case.

**Comment by justhchung** [comment]
Doc updated here: https://docs.microsoft.com/en-us/azure/devops/server/upgrade/get-started?view=azure-devops-2020
