### ISSUE TITLE
::: moniker range=">= azure-devops-2019" in article

### ISSUE THREAD

**Issue by Rutix** [MicrosoftDocs/azure-devops-server-docs#40]
The article shows " ::: moniker range="&gt;= azure-devops-2019" "
::: moniker range="&gt;= azure-devops-2019" ## Configuration options: Basic, Advanced and Azure

I can't find the md's on github so can't send in a PR to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8513ef18-5fc7-ef6c-a671-30943022af39
* Version Independent ID: 8936e3dc-af12-3a32-9869-26c4a8f0975b
* Content: [Install and configure - Azure DevOps Server & TFS](https://docs.microsoft.com/en-us/azure/devops/server/install/get-started?view=azure-devops#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2finstall%2fget-started.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2finstall%2fget-started.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Technology: **tfs-admin**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
Fixing and closing this issue.
