### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by evakili** [MicrosoftDocs/azure-devops-server-docs#46]
"Team and project notifications" link on the first section is dead:
https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-team-notificationss

There is a typo (redundant 's') at the end of the address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a63327db-2058-c35d-5d7f-83dc94696d3a
* Version Independent ID: e6b0d7ea-ec11-5013-5e96-08547dccb55d
* Content: [Configure an SMTP server - Azure DevOps Server & TFS](https://docs.microsoft.com/en-us/azure/devops/server/admin/setup-customize-alerts?view=azure-devops#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fadmin%2fsetup-customize-alerts.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fadmin%2fsetup-customize-alerts.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Technology: **tfs-admin**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
Fixing and closing this issue.
