### ISSUE TITLE
Typos in the Expect the best, prepare for the worst section:

### ISSUE THREAD

**Issue by richj** [MicrosoftDocs/azure-devops-server-docs#50]
[Enter feedback here]
Typos in the Expect the best, prepare for the worst section:

missing spaces-

We have been using scheduled backups to ensure that we always have backups in place in case something goes wrong.

Because we are moving to new hardware anyways, we will not bother setting up a separate pre-production **environmentto** do our dry run. Instead, we will use that new hardware to do a dry run first, and **thenwe** will wipe everything clean and use it again for the 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d859aed2-d181-a41d-3c58-9b86174c5b55
* Version Independent ID: 55853747-f11a-bd25-afb7-c3d9e8e374ba
* Content: [Upgrade TFS - TFS](https://docs.microsoft.com/en-us/azure/devops/server/upgrade/walkthrough?view=tfs-2015&viewFallbackFrom=azure-devops)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fupgrade%2fwalkthrough.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/tfs-docs-pr?path=%2fdocs%2fupgrade%2fwalkthrough.md&version=GBlive&_a=contents)
* Product: **devops-server**
* Technology: **tfs-admin**
* Git Login: **aaronhallberg**
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
Fixing and closing this issue
