### ISSUE TITLE
Q&A : compatibility with real Azure DevOps

### ISSUE THREAD

**Issue by tene666** [MicrosoftDocs/azure-devops-server-docs#65]
Is this product compatible with the actual online version of Azure DevOps? 
In other words: can it be used to host a local cache of rather big TFVC repo migrated over from on prem older TFS to Azure DevOps? It is especially painful for any newcomers or when branching, as downloading bigger chunks of code inevitably triggers throttling on Azure DevOps side, and the whole process takes unnecessarily long.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1b119c-e0a8-5143-bece-d2d0b8556bf6
* Version Independent ID: d819bd4f-5272-d350-348e-dd00cc9417c3
* Content: [How to install Azure DevOps Proxy Server - Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/server/install/install-proxy-setup-remote?view=azure-devops)
* Content Source: [docs/install/install-proxy-setup-remote.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/install/install-proxy-setup-remote.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by Styxxy** [comment]
Any information on this?
Ping @aaronhallberg 

For the time being, I also logged a request at the developer community: https://developercommunity.visualstudio.com/content/problem/818233/is-the-azure-devops-proxy-server-compatible-with-a.html

Update
@tene666 It seems in the Q&A that is supported, though it is quite a short answer. Still good to be verified.
> **Q: Does the proxy server fully support caching against dev.azure.com?**
> A: Yes

**Comment by aaronhallberg** [comment]
Yes, the proxy supports caching files from Azure DevOps organizations. Sorry for the slow response.

**Comment by vrajroutu** [comment]
What is the process ? I get this issue when setting up a proxy for AzureDevOps

![image](https://user-images.githubusercontent.com/22155528/79278410-a30e7e00-7e79-11ea-9b87-0645acbc97d9.png)

**Comment by Styxxy** [comment]
@kishorerv93 You should specify the full url, https://dev.azure.com/org
