### ISSUE TITLE
DevOps Server 2019 support for SQL 2019?

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/azure-devops-server-docs#71]
Hi All,

I know SQL 2019 just hit general availability, but I was curious if it can be added to the support list for Azure DevOps Server 2019?  My managers are going to ask me about this soon, and I would like to have an answer or at least tentative idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf58945-edff-cb3b-ab71-d45d480f1044
* Version Independent ID: 8a1c8ac9-a829-837b-5e52-81766c1f545e
* Content: [Requirements for setup, upgrade, and administration - Azure DevOps Server & TFS](https://docs.microsoft.com/en-us/azure/devops/server/requirements?view=azure-devops)
* Content Source: [docs/requirements.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/requirements.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by renrenproject** [comment]
I recently tried and the answer is nope!!

**Comment by PrometheusRising1** [comment]
Any reply on this?

**Comment by eriawan** [comment]
On [today's docs](https://docs.microsoft.com/azure/devops/server/requirements?view=azure-devops) it says it supports SQL Server 2019:

![image](https://user-images.githubusercontent.com/8773147/73719262-717a8780-4751-11ea-9b0f-820faa6a2d12.png)

But this requires installing Azure DevOps Server update 1.1 as described above.
