### ISSUE TITLE
link not working 

### ISSUE THREAD

**Issue by Abinell** [MicrosoftDocs/azure-devops-server-docs#82]
Below link is not working 
https://docs.microsoft.com/en-us/azure/devops/settings/about-settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58706ad4-8f9d-8330-f7c7-532ee5e89f4a
* Version Independent ID: 7368607e-5924-8039-1105-bc55878429dd
* Content: [Add administrators - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/admin/add-administrator?view=azure-devops#feedback)
* Content Source: [docs/admin/add-administrator.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/admin/add-administrator.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
@Abinell  - Thank you for the correction. I'm updating the article to correct the link.
