### ISSUE TITLE
TFSSecurity is Depricated for Azure DevOps Service

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/azure-devops-server-docs#88]
Hi team,

This Tool may still work for some scenarios, but it is deprecated and unsupported for Azure DevOps Service (It is still the correct tool for On Premise installs).

Can we please Remove "Use with Azure DevOps Services" section (and have it fall back to OnPrem versions if the service is picked in the Version drop down)? 

We should also add a note that explains that this tool is deprecated for Azure DevOps Services and that the recommended method to make changes is either via the Web UI, or the Rest Apis: https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-5.1 

Again, this tool has not been blocked but it can no longer fulfill all scenarios that this article advertises for all users, and per the developers is no longer supported for the Service, ONLY for the On Prem version of the product.

Please let me know if you have any questions!

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6f36e44-f157-3ff6-bdc9-38e90535fe97
* Version Independent ID: 39e507c4-9812-16fb-f0c1-0583b39fb1c7
* Content: [Change groups & permissions, TFSSecurity - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/command-line/tfssecurity-cmd?view=azure-devops#use-with-azure-devops-services)
* Content Source: [docs/command-line/tfssecurity-cmd.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/command-line/tfssecurity-cmd.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
@SamGrantham - I'm updating the topic per your feedback with this PR: https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/pull/41.
