### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by MarRich1** [MicrosoftDocs/azure-devops-server-docs#99]
https://docs.microsoft.com/en-us/azure/devops/server/install/install-proxy-setup-remote?view=azure-devops#configure-azure-devops-proxy-server-1

The "blog post" link is a dead link

![image](https://user-images.githubusercontent.com/50577700/83839265-d8a64980-a6fb-11ea-94af-03362c5bf807.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1b119c-e0a8-5143-bece-d2d0b8556bf6
* Version Independent ID: d819bd4f-5272-d350-348e-dd00cc9417c3
* Content: [Install Proxy Server - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/server/install/install-proxy-setup-remote?view=azure-devops)
* Content Source: [docs/install/install-proxy-setup-remote.md](https://github.com/MicrosoftDocs/azure-devops-server-docs-pr/blob/live/docs/install/install-proxy-setup-remote.md)
* Product: **devops-server**
* Technology: **tfs-admin**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by KathrynEE** [comment]
@MarRich1 - Thank you for the feedback. I'm updating the article to point to the correct post, now archived, [Proxy Upgrades: How to Verify Skipped Proxy Endpoints](https://docs.microsoft.com/en-us/archive/blogs/tfsao/proxy-upgrades-how-to-verify-skipped-proxy-endpoints).
